package com.buildboard.constants;

public interface AppConstant {
    String INTENT_SELECTED_ITEM = "intent_selected_item";
    String INTENT_TITLE = "intent_title";
    String DATA = "data";
    int CONTACT_MODE_REQUEST_CODE = 8;
    int USER_TYPE_REQUEST_CODE = 9;
    int CONTRACTOR_TYPE_REQUEST_CODE = 10;
    int WORKING_AREA_REQUEST_CODE = 11;
    int CARD_TYPE_REQUEST_CODE = 12;
    int PLACE_PICKER_REQUEST = 201;
    int IMAGE_UPLOAD_REQUEST_CODE = 200;
    int REQUEST_PERMISSION_CODE = 300;
    int FILE_SELECT_CODE = 0;
    int ERROR_CODE = 200;

    String SUCCESS = "success";
    String ACCESS_TOKEN = "access_token";
    String IS_LOGIN = "is_login";
    String ROLE_CONTRACTOR = "contractor";
    String SESSION_ID = "sessionId";
    String IS_CONTRACTOR = "is_contractor";
    String IS_CONSUMER = "is_consumer";
    String USER_ID = "user_id";
    String ROBOTO_BOLD = "fonts/Roboto-Bold.ttf";
    String ROBOTO_LIGHT = "fonts/Roboto-Light.ttf";
    String ROBOTO_REGULAR = "fonts/Roboto-Regular.ttf";
    String ROBOTO_MEDIUM = "fonts/Roboto-Medium.ttf";
    String LOGOUT = "logout";
    String INTENT_IMAGE_URL = "intent_image_url";
    String INTENT_PROVIDER = "intent_provider";
    String INTENT_PROVIDER_ID = "intent_provider_id";
    String INTENT_EMAIL = "intent_email";
    String INTENT_FIRST_NAME = "intent_first_name";
    String INTENT_LAST_NAME = "intent_last_name";
    String INTENT_WORK_TYPE_ID = "intent_work_type_id";
    String INTENT_FACEBOOK_TOKEN = "intent_facebook_token";
    String STATUS_OPEN = "open";
    String STATUS_COMPLETED = "completed";
    String STATUS_SAVED = "saved";
    String STATUS_CURRENT = "current";
    String STATUS_LOST = "lost";
    String PHONE = "phone";
    String EMAIL = "email";
    String FACEBOOK_TOKEN = "facebook_token";

    String TYPE_DROPDOWN = "dropDown";
    String TYPE_TEXT = "text";
    String TYPE_TEXT_VIEW = "textView";
    String TYPE_ATTACHMENT = "attachment";
    String TEXT_ATTACHMENT = "Attachments";
    String TEXT_REQUIREMENTS = "Requirements";
    String TYPE_MULTIPLE_ATTACHMENT = "multiple_attachment";

    String KEY_INSURANCE_DOLLAR_AMOUNT = "Insurance Dollar Amount";
    String KEY_ATTACHMENT_INSURANCE = "Attachment(Pdf/Document/Photo Of Insurence Document)";
    String KEY_LIABILITY = "Liability Insurance";
    String KEY_CERTIFYING = "Certifying Body";
    String KEY_CERTFICATION_NUMBER = "Certification Number";
    String KEY_CERTFICATION_DESCRIPTION = "Certification Brief Description";
    String KEY_ATTACHMENT_CERTIFICATION = "Attachment(Pdf/Document/Photo Of Certification Document)";
    String KEY_CITY = "City";
    String KEY_BOND_NUMBER = "Bond Number";
    String KEY_BOND_DOLLAR_AMOUNT = "Bond Dollar Amount";
    String KEY_ATTACHMENT_BOND = "Attachment(Pdf/Photo Of Bond Certificate)";
    String KEY_STATE = "State";
    String KEY_LICENSE_NUMBER = "License Number";
    String KEY_ATTACHMENT_BUSINESS = "Attachment(Pdf/Document/Photo Of Business License)";
    String KEY_INSURANCE_PROVIDER = "Insurance Provider";
    String KEY_NAME = "name";
    String KEY_DESCRIPTION = "description";
    String KEY_WORK_PERFORMED = "workPerformed";
    String KEY_ATTACHMENT = "attachment";

    String INTENT_USER_ID = "intent_userid";
    String TERMS_OF_SERVICES_LINK = "http://dashboard.buildboardinc.biz/terms-and-condition";
    String PRIVACY_POLICY_LINK = "http://dashboard.buildboardinc.biz/privacy-policy";
    String FAQ_LINK = "http://dashboard.buildboardinc.biz/faqs";
    String CONTACT_US = "http://dashboard.buildboardinc.biz/#contact-us";

    int REQUEST_IMAGE_CAPTURE = 1;
    String FIRST_NAME = "first_name";
    String LAST_NAME = "last_name";
    String INPUT_PATTERN = "yyyy-MM-dd";
    String OUTPUT_PATTERN = "dd MMM yyyy";
    String INTENT_TRENDING_USER_ID = "intent_trending_user_id";
    String INTENT_PROJECT_TYPE_DATA = "intent_project_type";
    String INTENT_SELECTED_CATEGORY = "intent_selected_category";
    String INTENT_CREATE_PROJECT_TASK = "intent_selected_task";
    String INTENT_SELECTED_PROJECT_SUB_CATEGORY = "intent_selected_project_sub_category";
}